/** Shared layout styles for add/import form sections (Daniyal). */

export const formStyles = {
  panel: {
    background: "#14181F",
    border: "1px solid #2A303B",
    borderRadius: "12px",
    padding: "1.25rem",
    marginBottom: "1.25rem",
  },
  panelHeader: {
    display: "flex",
    gap: "0.85rem",
    alignItems: "flex-start",
    marginBottom: "1rem",
  },
  panelStep: {
    fontFamily: "ui-monospace, SFMono-Regular, Consolas, monospace",
    fontSize: "11px",
    color: "#D9A441",
    border: "1px solid #2A303B",
    borderRadius: "6px",
    padding: "0.25rem 0.45rem",
    flexShrink: 0,
  },
  panelTitle: {
    fontSize: "15px",
    fontWeight: 500,
    margin: "0 0 0.25rem",
    color: "#E7E5DE",
  },
  panelDesc: {
    fontSize: "13px",
    color: "#B7B4AA",
    lineHeight: 1.5,
    margin: 0,
  },
  fileRow: { marginBottom: "0.75rem" },
  fileLabel: {
    display: "inline-block",
    background: "#1C222C",
    border: "1px solid #2A303B",
    color: "#B7B4AA",
    padding: "0.5rem 0.9rem",
    borderRadius: "8px",
    fontSize: "13px",
    cursor: "pointer",
  },
  fileInput: { display: "none" },
  textarea: {
    width: "100%",
    minHeight: "100px",
    background: "#1C222C",
    border: "1px solid #2A303B",
    color: "#E7E5DE",
    borderRadius: "8px",
    padding: "0.75rem",
    fontFamily: "ui-monospace, SFMono-Regular, Consolas, monospace",
    fontSize: "12px",
    boxSizing: "border-box",
  },
  actionRow: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
    marginTop: "0.75rem",
  },
  primaryBtn: {
    background: "#D9A441",
    border: "none",
    color: "#14181F",
    padding: "0.6rem 1.1rem",
    borderRadius: "8px",
    fontSize: "13px",
    fontWeight: 500,
    cursor: "pointer",
  },
  hint: { fontSize: "13px", color: "#B7B4AA" },
  parseError: {
    marginTop: "0.75rem",
    fontSize: "13px",
    color: "#F09595",
  },
  previewBox: {
    background: "#1C222C",
    border: "1px solid #2A303B",
    borderRadius: "8px",
    padding: "0.75rem",
    fontSize: "12px",
    fontFamily: "ui-monospace, SFMono-Regular, Consolas, monospace",
    color: "#B7B4AA",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "0.85rem",
  },
  fieldGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "0.45rem",
  },
  fieldLabel: {
    fontFamily: "ui-monospace, SFMono-Regular, Consolas, monospace",
    fontSize: "11px",
    color: "#8C8A80",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
  },
  input: {
    width: "100%",
    boxSizing: "border-box",
    background: "#1C222C",
    border: "1px solid #2A303B",
    color: "#E7E5DE",
    padding: "0.55rem 0.75rem",
    borderRadius: "8px",
    fontSize: "14px",
  },
  formRow: { display: "flex", gap: "0.6rem", flexWrap: "wrap" },
  formRowItem: { flex: "1 1 200px", minWidth: 0 },
  tagFilterRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.5rem",
  },
  tagChip: {
    background: "transparent",
    border: "1px solid",
    padding: "0.35rem 0.7rem",
    borderRadius: "999px",
    fontSize: "12px",
    cursor: "pointer",
  },
};
